[project]
name = "pokemon-rest-api-getter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyside6>=6.8.2.1",
    "requests>=2.32.3",
]
